export const dbShirts = [
  {
    id: 1,
    name: "Great Fox",
    description:
      "Ideal para cualquier ocasión, esta playera clásica blanca de algodón ofrece comodidad y estilo atemporal.",
    price: 100,
    category: "phrase",
    trend: true,
    popular: true,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/shirts/shirt-1.png",
  },
  {
    id: 2,
    name: "Red Animal Shirt",
    description:
      "Añade un toque vintage a tu guardarropa con esta playera gráfica retro, con un diseño inspirado en los años 80.",
    price: 100,
    category: "Woman",
    trend: true,
    popular: true,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/shirts/shirt-2.png",
  },
  {
    id: 3,
    name: "The cube",
    description:
      "Perfecta para el gimnasio o actividades al aire libre, esta playera deportiva de secado rápido mantiene la frescura y comodidad.",
    price: 100,
    category: "Men",
    trend: true,
    popular: true,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/shirts/shirt-3.png",
  },
  {
    id: 4,
    name: "Heart Shirt",
    description:
      "Luce fresco y a la moda con esta playera de algodón con un encantador estampado floral, ideal para los días soleados.",
    price: 120,
    category: "Teens",
    trend: true,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/shirts/shirt-4.png",
  },
  {
    id: 5,
    name: "Text Shirt",
    description:
      "Un esencial en cualquier guardarropa, esta playera negra básica combina con todo y es perfecta para cualquier ocasión.",
    price: 120,
    category: "Teens",
    trend: true,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/shirts/shirt-5.png",
  },
  {
    id: 6,
    name: "Figures Shirt",
    description:
      "Una playera de algodón de estilo moderno, con un diseño elegante y una pintura fresca, ideal para cualquier ocasión.",
    price: 120,
    category: "Teens",
    trend: true,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/shirts/shirt-9.png",
  },
];
