export const dbShirts = [
  {
    id: 1,
    name: "Great Fox",
    description:
      "Ideal para cualquier ocasión, esta playera clásica blanca de algodón ofrece comodidad y estilo atemporal.",
    price: 100,
    category: "teens",
    trend: true,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/teens/model-1.webp",
  },
  {
    id: 2,
    name: "Red Animal Shirt",
    description:
      "Añade un toque vintage a tu guardarropa con esta playera gráfica retro, con un diseño inspirado en los años 80.",
    price: 100,
    category: "teens",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/teens/model-2.webp",
  },
  {
    id: 3,
    name: "The cube",
    description:
      "Perfecta para el gimnasio o actividades al aire libre, esta playera deportiva de secado rápido mantiene la frescura y comodidad.",
    price: 100,
    category: "teens",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/teens/model-3.webp",
  },
  {
    id: 4,
    name: "Heart Shirt",
    description:
      "Luce fresco y a la moda con esta playera de algodón con un encantador estampado floral, ideal para los días soleados.",
    price: 120,
    category: "teens",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/teens/model-4.webp",
  },
  {
    id: 5,
    name: "Text Shirt",
    description:
      "Un esencial en cualquier guardarropa, esta playera negra básica combina con todo y es perfecta para cualquier ocasión.",
    price: 120,
    category: "teens",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/teens/model-5.webp",
  },
  {
    id: 6,
    name: "Figures Shirt",
    description:
      "Una playera de algodón de estilo moderno, con un diseño elegante y una pintura fresca, ideal para cualquier ocasión.",
    price: 120,
    category: "teens",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/teens/model-6.webp",
  },
  {
    id: 7,
    name: "The cube",
    description:
      "Perfecta para el gimnasio o actividades al aire libre, esta playera deportiva de secado rápido mantiene la frescura y comodidad.",
    price: 100,
    category: "color",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/color/color-1.webp",
  },
  {
    id: 8,
    name: "Red Animal Shirt",
    description:
      "Añade un toque vintage a tu guardarropa con esta playera gráfica retro, con un diseño inspirado en los años 80.",
    price: 100,
    category: "color",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/color/color-2.webp",
  },
  {
    id: 9,
    name: "Heart Shirt",
    description:
      "Luce fresco y a la moda con esta playera de algodón con un encantador estampado floral, ideal para los días soleados.",
    price: 120,
    category: "color",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/color/color-3.webp",
  },
  {
    id: 10,
    name: "The cube",
    description:
      "Perfecta para el gimnasio o actividades al aire libre, esta playera deportiva de secado rápido mantiene la frescura y comodidad.",
    price: 100,
    category: "color",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/color/color-4.webp",
  },
  {
    id: 11,
    name: "Red Animal Shirt",
    description:
      "Añade un toque vintage a tu guardarropa con esta playera gráfica retro, con un diseño inspirado en los años 80.",
    price: 100,
    category: "color",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/color/color-5.webp",
  },
  {
    id: 12,
    name: "Heart Shirt",
    description:
      "Luce fresco y a la moda con esta playera de algodón con un encantador estampado floral, ideal para los días soleados.",
    price: 120,
    category: "color",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/color/color-6.webp",
  },
  {
    id: 13,
    name: "The cube",
    description:
      "Perfecta para el gimnasio o actividades al aire libre, esta playera deportiva de secado rápido mantiene la frescura y comodidad.",
    price: 100,
    category: "funny",
    trend: false,
    popular: true,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/funny/funny-1.webp",
  },
  {
    id: 14,
    name: "Red Animal Shirt",
    description:
      "Añade un toque vintage a tu guardarropa con esta playera gráfica retro, con un diseño inspirado en los años 80.",
    price: 100,
    category: "funny",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/funny/funny-2.webp",
  },
  {
    id: 15,
    name: "The cube",
    description:
      "Perfecta para el gimnasio o actividades al aire libre, esta playera deportiva de secado rápido mantiene la frescura y comodidad.",
    price: 100,
    category: "funny",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/funny/funny-3.webp",
  },
  {
    id: 16,
    name: "Red Animal Shirt",
    description:
      "Añade un toque vintage a tu guardarropa con esta playera gráfica retro, con un diseño inspirado en los años 80.",
    price: 100,
    category: "funny",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/funny/funny-4.webp",
  },
  {
    id: 17,
    name: "Heart Shirt",
    description:
      "Luce fresco y a la moda con esta playera de algodón con un encantador estampado floral, ideal para los días soleados.",
    price: 120,
    category: "funny",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/funny/funny-5.webp",
  },
  {
    id: 18,
    name: "The cube",
    description:
      "Perfecta para el gimnasio o actividades al aire libre, esta playera deportiva de secado rápido mantiene la frescura y comodidad.",
    price: 100,
    category: "funny",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/funny/funny-6.webp",
  },
  {
    id: 19,
    name: "Red Animal Shirt",
    description:
      "Añade un toque vintage a tu guardarropa con esta playera gráfica retro, con un diseño inspirado en los años 80.",
    price: 100,
    category: "figures",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/figures/figure-1.webp",
  },
  {
    id: 20,
    name: "Heart Shirt",
    description:
      "Luce fresco y a la moda con esta playera de algodón con un encantador estampado floral, ideal para los días soleados.",
    price: 120,
    category: "figures",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/figures/figure-2.webp",
  },
  {
    id: 21,
    name: "The cube",
    description:
      "Perfecta para el gimnasio o actividades al aire libre, esta playera deportiva de secado rápido mantiene la frescura y comodidad.",
    price: 100,
    category: "figures",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/figures/figure-3.webp",
  },
  {
    id: 22,
    name: "Red Animal Shirt",
    description:
      "Añade un toque vintage a tu guardarropa con esta playera gráfica retro, con un diseño inspirado en los años 80.",
    price: 100,
    category: "figures",
    trend: false,
    popular: true,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/figures/figure-4.webp",
  },
  {
    id: 23,
    name: "Heart Shirt",
    description:
      "Luce fresco y a la moda con esta playera de algodón con un encantador estampado floral, ideal para los días soleados.",
    price: 120,
    category: "figures",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/figures/figure-5.webp",
  },
  {
    id: 24,
    name: "The cube",
    description:
      "Perfecta para el gimnasio o actividades al aire libre, esta playera deportiva de secado rápido mantiene la frescura y comodidad.",
    price: 100,
    category: "figures",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/figures/figure-6.webp",
  },
  {
    id: 25,
    name: "Red Animal Shirt",
    description:
      "Añade un toque vintage a tu guardarropa con esta playera gráfica retro, con un diseño inspirado en los años 80.",
    price: 100,
    category: "logo",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/logo/logo-1.webp",
  },
  {
    id: 26,
    name: "Heart Shirt",
    description:
      "Luce fresco y a la moda con esta playera de algodón con un encantador estampado floral, ideal para los días soleados.",
    price: 120,
    category: "logo",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/logo/logo-2.webp",
  },
  {
    id: 27,
    name: "The cube",
    description:
      "Perfecta para el gimnasio o actividades al aire libre, esta playera deportiva de secado rápido mantiene la frescura y comodidad.",
    price: 100,
    category: "logo",
    trend: true,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/logo/logo-3.webp",
  },
  {
    id: 28,
    name: "Red Animal Shirt",
    description:
      "Añade un toque vintage a tu guardarropa con esta playera gráfica retro, con un diseño inspirado en los años 80.",
    price: 100,
    category: "logo",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/logo/logo-4.webp",
  },
  {
    id: 29,
    name: "Heart Shirt",
    description:
      "Luce fresco y a la moda con esta playera de algodón con un encantador estampado floral, ideal para los días soleados.",
    price: 120,
    category: "logo",
    trend: true,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/logo/logo-5.webp",
  },
  {
    id: 30,
    name: "The cube",
    description:
      "Perfecta para el gimnasio o actividades al aire libre, esta playera deportiva de secado rápido mantiene la frescura y comodidad.",
    price: 100,
    category: "logo",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/logo/logo-6.webp",
  },
  {
    id: 31,
    name: "Red Animal Shirt",
    description:
      "Añade un toque vintage a tu guardarropa con esta playera gráfica retro, con un diseño inspirado en los años 80.",
    price: 100,
    category: "men",
    trend: true,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/men/men-1.webp",
  },
  {
    id: 32,
    name: "Heart Shirt",
    description:
      "Luce fresco y a la moda con esta playera de algodón con un encantador estampado floral, ideal para los días soleados.",
    price: 120,
    category: "men",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/men/men-2.webp",
  },
  {
    id: 33,
    name: "The cube",
    description:
      "Perfecta para el gimnasio o actividades al aire libre, esta playera deportiva de secado rápido mantiene la frescura y comodidad.",
    price: 100,
    category: "men",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/men/men-3.webp",
  },
  {
    id: 34,
    name: "Red Animal Shirt",
    description:
      "Añade un toque vintage a tu guardarropa con esta playera gráfica retro, con un diseño inspirado en los años 80.",
    price: 100,
    category: "men",
    trend: true,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/men/men-4.webp",
  },
  {
    id: 35,
    name: "Heart Shirt",
    description:
      "Luce fresco y a la moda con esta playera de algodón con un encantador estampado floral, ideal para los días soleados.",
    price: 120,
    category: "men",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/men/men-5.webp",
  },
  {
    id: 36,
    name: "The cube",
    description:
      "Perfecta para el gimnasio o actividades al aire libre, esta playera deportiva de secado rápido mantiene la frescura y comodidad.",
    price: 100,
    category: "men",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/men/men-6.webp",
  },
  {
    id: 37,
    name: "Red Animal Shirt",
    description:
      "Añade un toque vintage a tu guardarropa con esta playera gráfica retro, con un diseño inspirado en los años 80.",
    price: 100,
    category: "women",
    trend: false,
    popular: true,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/women/woman-1.webp",
  },
  {
    id: 38,
    name: "Heart Shirt",
    description:
      "Luce fresco y a la moda con esta playera de algodón con un encantador estampado floral, ideal para los días soleados.",
    price: 120,
    category: "women",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/women/woman-2.webp",
  },
  {
    id: 39,
    name: "The cube",
    description:
      "Perfecta para el gimnasio o actividades al aire libre, esta playera deportiva de secado rápido mantiene la frescura y comodidad.",
    price: 100,
    category: "women",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/women/woman-3.webp",
  },
  {
    id: 40,
    name: "Red Animal Shirt",
    description:
      "Añade un toque vintage a tu guardarropa con esta playera gráfica retro, con un diseño inspirado en los años 80.",
    price: 100,
    category: "women",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/women/woman-4.webp",
  },
  {
    id: 41,
    name: "Heart Shirt",
    description:
      "Luce fresco y a la moda con esta playera de algodón con un encantador estampado floral, ideal para los días soleados.",
    price: 120,
    category: "women",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/women/woman-5.webp",
  },
  {
    id: 42,
    name: "The cube",
    description:
      "Perfecta para el gimnasio o actividades al aire libre, esta playera deportiva de secado rápido mantiene la frescura y comodidad.",
    price: 100,
    category: "women",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/women/woman-6.webp",
  },
  {
    id: 43,
    name: "Red Animal Shirt",
    description:
      "Añade un toque vintage a tu guardarropa con esta playera gráfica retro, con un diseño inspirado en los años 80.",
    price: 100,
    category: "phrase",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/phrase/text-1.webp",
  },
  {
    id: 44,
    name: "Heart Shirt",
    description:
      "Luce fresco y a la moda con esta playera de algodón con un encantador estampado floral, ideal para los días soleados.",
    price: 120,
    category: "phrase",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/phrase/text-2.webp",
  },
  {
    id: 45,
    name: "The cube",
    description:
      "Perfecta para el gimnasio o actividades al aire libre, esta playera deportiva de secado rápido mantiene la frescura y comodidad.",
    price: 100,
    category: "phrase",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/phrase/text-3.webp",
  },
  {
    id: 46,
    name: "Red Animal Shirt",
    description:
      "Añade un toque vintage a tu guardarropa con esta playera gráfica retro, con un diseño inspirado en los años 80.",
    price: 100,
    category: "phrase",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/phrase/text-4.webp",
  },
  {
    id: 47,
    name: "Heart Shirt",
    description:
      "Luce fresco y a la moda con esta playera de algodón con un encantador estampado floral, ideal para los días soleados.",
    price: 120,
    category: "phrase",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/phrase/text-5.webp",
  },
  {
    id: 48,
    name: "The cube",
    description:
      "Perfecta para el gimnasio o actividades al aire libre, esta playera deportiva de secado rápido mantiene la frescura y comodidad.",
    price: 100,
    category: "phrase",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/phrase/text-6.webp",
  },
  {
    id: 49,
    name: "Red Animal Shirt",
    description:
      "Añade un toque vintage a tu guardarropa con esta playera gráfica retro, con un diseño inspirado en los años 80.",
    price: 100,
    category: "unique",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/unique/unique-1.webp",
  },
  {
    id: 50,
    name: "Heart Shirt",
    description:
      "Luce fresco y a la moda con esta playera de algodón con un encantador estampado floral, ideal para los días soleados.",
    price: 120,
    category: "unique",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/unique/unique-2.webp",
  },
  {
    id: 51,
    name: "The cube",
    description:
      "Perfecta para el gimnasio o actividades al aire libre, esta playera deportiva de secado rápido mantiene la frescura y comodidad.",
    price: 100,
    category: "unique",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/unique/unique-3.webp",
  },
  {
    id: 52,
    name: "Red Animal Shirt",
    description:
      "Añade un toque vintage a tu guardarropa con esta playera gráfica retro, con un diseño inspirado en los años 80.",
    price: 100,
    category: "unique",
    trend: true,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/unique/unique-4.webp",
  },
  {
    id: 53,
    name: "Heart Shirt",
    description:
      "Luce fresco y a la moda con esta playera de algodón con un encantador estampado floral, ideal para los días soleados.",
    price: 120,
    category: "unique",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/unique/unique-5.webp",
  },
  {
    id: 54,
    name: "The cube",
    description:
      "Perfecta para el gimnasio o actividades al aire libre, esta playera deportiva de secado rápido mantiene la frescura y comodidad.",
    price: 100,
    category: "unique",
    trend: false,
    popular: false,
    size: ["S", "M", "L", "XL"],
    stock: 10,
    image: "/unique/unique-6.webp",
  },
];

export const dbCollection = [
  {
    id: 1,
    name: "Color",
    bg: "bg-color",
    link: "/categories/color",
  },
  {
    id: 2,
    name: "Divertidas",
    bg: "bg-funny",
    link: "/categories/funny",
  },
  {
    id: 3,
    name: "Figuras",
    bg: "bg-images",
    link: "/categories/images",
  },
  {
    id: 5,
    name: "Logo",
    bg: "bg-logo",
    link: "/categories/logo",
  },
  {
    id: 6,
    name: "Hombres",
    bg: "bg-men",
    link: "/categories/men",
  },
  {
    id: 7,
    name: "Frases",
    bg: "bg-phrase",
    link: "/categories/phrase",
  },
  {
    id: 8,
    name: "Juvenil",
    bg: "bg-teens",
    link: "/categories/teens",
  },
  {
    id: 9,
    name: "Únicas",
    bg: "bg-unique",
    link: "/categories/unique",
  },
  {
    id: 10,
    name: "Mujeres",
    bg: "bg-women",
    link: "/categories/women",
  },
];
